#generates flat spectrum neutrons for validation studies

/CoBaLEP/generator/select GPS

/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 0. 0. -0.0001 cm
/gps/direction 1 0 0
/gps/ene/mono 1.0000 keV

#/gps/ene/type Lin
#/gps/ene/min 10 MeV
#/gps/ene/max 1000.0 MeV
#/gps/ene/gradient 0
#/gps/ene/intercept 1

#/vis/open HepRepFile
#/vis/drawVolume
#/vis/viewer/flush
#/vis/scene/add/trajectories
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/active true
#/vis/scene/add/hits
#/vis/scene/endOfEventAction accumulate


/run/beamOn 100000
