#generates monoenergetic muons for the neutron multiplicity study


/GUORE/generator/select GPS

/gps/particle mu-
/gps/pos/type Point
/gps/position 0.010001 0 0 m

/gps/direction 0 0 -1
/gps/ene/mono 300000.00 MeV

/vis/open HepRepFile
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/active true
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate


/run/beamOn 10
